namespace MysteryForest
{
     public enum Sound
     {
        GrassBiomAmbient = 0,
        AllEnemyDead = 1,
        MenuBackGroundMusic = 2,
        BattleBackGroundMusic = 3,
        FriendlyBackGroundMusic = 4,
        StoryModeBackGroundMusic = 5,
        PlayerResiveDamage = 6,
        PlayerSteps = 7,
        PlayerItemPickUp = 8,
        PlayerPotionUse = 9,
        PlayerThrowBomb = 10,
        PlayerAttackWithoutWeapon = 11,
        PlayerAttackSword = 12,
        PlayerAttackWand = 13,
        PlayerAttackSlingshot = 14,
        PlayerAttackBow = 15,
        HornetDamageResive = 16,
        HornetFly = 17,
        SquirrelDamageTaken = 18,
        SquirrelThrowCone = 19,
        HedgehogDamageResive = 20,
        HedgehogStun = 21,
        HedgehogCrash = 22,
        HedgehogRoll = 23,
        HedgehogRush = 24,
        StumpChestOpen = 25,
        KeyUse = 26,
        WinScreenSound = 27,
        LoseScreenSound = 28,
        MineBombExplosion = 29,
        CoctailBombExplosion = 30,
        BlastBombExplosion = 31,
        MenuButtonClicked = 32,
        SnakeShoot = 33,
        SnakeJump = 34,
        SnakeRushPrepare = 35,
        SnakeMeleeAttack = 36,
        SnakeDamageResive = 37,
        SnakeProjectileHit = 38,
        SnakeDead = 39,
        SnakeLanding = 40,
        OwlFly = 41,
        ArrowSound = 42
            
     }
}